# Generated by Django 5.0.6 on 2024-08-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['dish', 'created_at'], 'verbose_name': 'Відгук', 'verbose_name_plural': 'Відгуки'},
        ),
    ]
