# Generated by Django 5.0.6 on 2024-08-13 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['category'], 'verbose_name': 'Страва', 'verbose_name_plural': 'Страви'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.category', verbose_name='категорія'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='В наявності'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dish_images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
    ]
